<?php
/**
 * One-page installer for hosting (and XAMPP).
 * URL: https://prakandd-thailand.com/admin/install.php
 */

declare(strict_types=1);

$lockFile = __DIR__ . '/install.lock';
$configLocal = __DIR__ . '/config.local.php';
$force = isset($_GET['force']) && $_GET['force'] === '1';

// Detect public paths from this script location
$scriptDir = str_replace('\\', '/', dirname($_SERVER['SCRIPT_NAME'] ?? '/admin'));
$adminUrl = rtrim($scriptDir, '/') ?: '/admin';
$siteUrl = dirname($adminUrl);
if ($siteUrl === '/' || $siteUrl === '\\' || $siteUrl === '.') {
    $siteUrl = '';
}

$step = 'form';
$message = '';
$errors = [];
$seedStats = null;

$prefill = [
    'db_host' => 'localhost',
    'db_name' => 'agent1501',
    'db_user' => '',
    'db_pass' => '',
    'admin_user' => 'admin',
    'admin_pass' => 'admin123',
    'admin_name' => 'Administrator',
    'run_seed' => '1',
];

if (is_file($lockFile) && !$force && $_SERVER['REQUEST_METHOD'] !== 'POST') {
    $step = 'locked';
}

/**
 * Split SQL file into executable statements (skips CREATE DATABASE / USE).
 */
function installSplitSql(string $sql): array {
    $sql = preg_replace('/^CREATE DATABASE.*?;\s*/im', '', $sql) ?? $sql;
    $sql = preg_replace('/^USE\s+.*?;\s*/im', '', $sql) ?? $sql;
    $parts = preg_split('/;\s*\n/', $sql) ?: [];
    $out = [];
    foreach ($parts as $part) {
        $part = trim($part);
        if ($part === '' || str_starts_with($part, '--')) {
            continue;
        }
        $out[] = $part;
    }
    return $out;
}

function installWriteConfig(array $data): void {
    $export = var_export($data, true);
    $php = "<?php\n/** Auto-generated by install.php — do not commit secrets */\nreturn {$export};\n";
    if (file_put_contents(__DIR__ . '/config.local.php', $php) === false) {
        throw new RuntimeException('เขียนไฟล์ config.local.php ไม่ได้ — ตรวจสิทธิ์โฟลเดอร์ admin/');
    }
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $prefill['db_host'] = trim((string) ($_POST['db_host'] ?? 'localhost'));
    $prefill['db_name'] = trim((string) ($_POST['db_name'] ?? ''));
    $prefill['db_user'] = trim((string) ($_POST['db_user'] ?? ''));
    $prefill['db_pass'] = (string) ($_POST['db_pass'] ?? '');
    $prefill['admin_user'] = trim((string) ($_POST['admin_user'] ?? 'admin'));
    $prefill['admin_pass'] = (string) ($_POST['admin_pass'] ?? '');
    $prefill['admin_name'] = trim((string) ($_POST['admin_name'] ?? 'Administrator'));
    $prefill['run_seed'] = isset($_POST['run_seed']) ? '1' : '';

    if ($prefill['db_host'] === '') $errors[] = 'กรุณากรอก DB Host';
    if ($prefill['db_name'] === '') $errors[] = 'กรุณากรอกชื่อฐานข้อมูล';
    if ($prefill['db_user'] === '') $errors[] = 'กรุณากรอก DB Username';
    if ($prefill['admin_user'] === '') $errors[] = 'กรุณากรอกชื่อผู้ใช้แอดมิน';
    if (strlen($prefill['admin_pass']) < 6) $errors[] = 'รหัสผ่านแอดมินอย่างน้อย 6 ตัวอักษร';

    if (!$errors) {
        try {
            // Connect without DB first (create if possible)
            $dsnServer = 'mysql:host=' . $prefill['db_host'] . ';charset=utf8mb4';
            $pdo = new PDO($dsnServer, $prefill['db_user'], $prefill['db_pass'], [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            ]);

            $dbName = $prefill['db_name'];
            try {
                $pdo->exec(
                    'CREATE DATABASE IF NOT EXISTS `' . str_replace('`', '``', $dbName) . '` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci'
                );
            } catch (Throwable $e) {
                // Shared hosting often forbids CREATE DATABASE — DB must already exist in cPanel
            }

            $pdo->exec('USE `' . str_replace('`', '``', $dbName) . '`');

            $sqlFile = __DIR__ . '/setup.sql';
            if (!is_file($sqlFile)) {
                throw new RuntimeException('ไม่พบไฟล์ setup.sql');
            }
            foreach (installSplitSql((string) file_get_contents($sqlFile)) as $stmt) {
                try {
                    $pdo->exec($stmt);
                } catch (Throwable $e) {
                    // Ignore duplicate table / key on re-install
                    $msg = $e->getMessage();
                    if (!str_contains($msg, 'already exists') && !str_contains($msg, 'Duplicate')) {
                        throw $e;
                    }
                }
            }

            installWriteConfig([
                'DB_HOST' => $prefill['db_host'],
                'DB_NAME' => $prefill['db_name'],
                'DB_USER' => $prefill['db_user'],
                'DB_PASS' => $prefill['db_pass'],
                'SITE_URL' => $siteUrl,
                'ADMIN_URL' => $adminUrl,
            ]);

            // Upsert admin user with chosen password
            $hash = password_hash($prefill['admin_pass'], PASSWORD_DEFAULT);
            $check = $pdo->prepare('SELECT id FROM admin_users WHERE username = ?');
            $check->execute([$prefill['admin_user']]);
            $existing = $check->fetch(PDO::FETCH_ASSOC);
            if ($existing) {
                $upd = $pdo->prepare('UPDATE admin_users SET password_hash = ?, display_name = ? WHERE id = ?');
                $upd->execute([$hash, $prefill['admin_name'], $existing['id']]);
            } else {
                $ins = $pdo->prepare('INSERT INTO admin_users (username, password_hash, display_name) VALUES (?,?,?)');
                $ins->execute([$prefill['admin_user'], $hash, $prefill['admin_name']]);
            }

            // Ensure default FAQ set if empty
            $faqCount = (int) $pdo->query('SELECT COUNT(*) FROM faq_items')->fetchColumn();
            if ($faqCount === 0) {
                $pdo->exec("INSERT INTO faq_items (question, answer, sort_order, is_active) VALUES
                    ('ประกันชีวิตคืออะไร และทำไมถึงสำคัญ?', 'ประกันชีวิตเป็นเครื่องมือทางการเงินที่ช่วยคุ้มครองครอบครัวของคุณในกรณีที่เกิดเหตุไม่คาดฝัน เป็นการวางแผนทางการเงินที่สำคัญเพื่อให้คนที่คุณรักมีความมั่นคงในอนาคต', 1, 1),
                    ('ต้องใช้เอกสารอะไรบ้างในการสมัครประกัน?', 'เอกสารที่ต้องใช้ ได้แก่ บัตรประชาชน สำเนาทะเบียนบ้าน และเอกสารทางการแพทย์ (ถ้ามี)', 2, 1),
                    ('สามารถเปลี่ยนแผนประกันได้หรือไม่?', 'สามารถเปลี่ยนแผนประกันได้ตามเงื่อนไขของกรมธรรม์ โดยติดต่อตัวแทนหรือฝ่ายบริการลูกค้า', 3, 1),
                    ('เคลมประกันใช้เวลานานเท่าไหร่?', 'ระยะเวลาในการพิจารณาเคลมโดยทั่วไปใช้เวลา 7-15 วันทำการ', 4, 1),
                    ('มีบริการปรึกษาฟรีหรือไม่?', 'มีบริการปรึกษาฟรีจากทีมผู้เชี่ยวชาญของเรา ติดต่อได้ผ่านแบบฟอร์ม โทรศัพท์ หรือ Line Official', 5, 1),
                    ('สามารถจ่ายเบี้ยประกันรายเดือนได้หรือไม่?', 'สามารถเลือกชำระเบี้ยได้หลายรูปแบบ ทั้งรายเดือน ราย 3 เดือน ราย 6 เดือน หรือรายปี ตามแผนที่คุณสมัคร', 6, 1),
                    ('ประกันคุ้มครองตั้งแต่เมื่อไหร่?', 'ความคุ้มครองเริ่มต้นตามเงื่อนไขในกรมธรรม์ โดยทั่วไปมีผลหลังอนุมัติและชำระเบี้ยงวดแรกเรียบร้อยแล้ว', 7, 1),
                    ('ยกเลิกกรมธรรม์ได้หรือไม่?', 'สามารถยกเลิกกรมธรรม์ได้ตามเงื่อนไขที่ระบุในกรมธรรม์ โดยแนะนำให้ปรึกษาตัวแทนก่อนตัดสินใจ', 8, 1)");
            }

            // Optional seed from published JS files
            if ($prefill['run_seed'] === '1') {
                // Bootstrap config constants for seed-import
                require_once __DIR__ . '/config.php';
                require_once __DIR__ . '/includes/db.php';
                require_once __DIR__ . '/includes/seed-import.php';
                $categories = require __DIR__ . '/seed-categories.php';
                $seedStats = runFullSeedImport($categories);
            }

            file_put_contents($lockFile, date('c') . " installed on {$_SERVER['HTTP_HOST']}\n");
            $step = 'success';
            $message = 'ติดตั้งเรียบร้อยแล้ว';
        } catch (Throwable $e) {
            $step = 'error';
            $message = $e->getMessage();
        }
    } else {
        $step = 'form';
    }
}

$loginHref = htmlspecialchars($adminUrl . '/login.php');
$seedHref = htmlspecialchars($adminUrl . '/seed.php');
$siteHome = htmlspecialchars(($siteUrl === '' ? '' : $siteUrl) . '/index.html');
?>
<!DOCTYPE html>
<html lang="th">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ติดตั้งระบบ — Agent Thailand</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <script>tailwind.config={theme:{extend:{colors:{brand:'#150f96','brand-light':'#2a1fbb'}}}}</script>
  <link rel="stylesheet" href="<?= htmlspecialchars($adminUrl) ?>/assets/admin.css">
</head>
<body class="admin-app flex items-center justify-center min-h-screen py-10">
  <div class="w-full max-w-xl p-6">
    <div class="admin-card p-8 shadow-lg">
      <div class="text-center mb-8">
        <div class="w-16 h-16 bg-brand/10 rounded-2xl flex items-center justify-center mx-auto mb-4">
          <svg class="w-8 h-8 text-brand" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M20.25 6.375c0 2.278-3.694 4.125-8.25 4.125S3.75 8.653 3.75 6.375m16.5 0c0-2.278-3.694-4.125-8.25-4.125S3.75 4.097 3.75 6.375m16.5 0v11.25c0 2.278-3.694 4.125-8.25 4.125s-8.25-1.847-8.25-4.125V6.375"/></svg>
        </div>
        <h1 class="text-2xl font-bold text-slate-800">ติดตั้งระบบ</h1>
        <p class="text-slate-500 mt-1 text-sm">prakandd-thailand.com · Agent Thailand</p>
      </div>

      <?php if ($step === 'locked'): ?>
        <div class="admin-alert-success mb-6">ติดตั้งแล้ว — ระบบพร้อมใช้งาน</div>
        <p class="text-sm text-slate-600 mb-4">ถ้าต้องการติดตั้งใหม่ ให้ลบไฟล์ <code class="bg-slate-100 px-1 rounded text-xs">admin/install.lock</code> หรือเปิดลิงก์พร้อม <code class="bg-slate-100 px-1 rounded text-xs">?force=1</code></p>
        <a href="<?= $loginHref ?>" class="admin-btn-primary w-full justify-center py-3">ไปหน้าเข้าสู่ระบบ</a>

      <?php elseif ($step === 'success'): ?>
        <div class="admin-alert-success mb-6"><?= htmlspecialchars($message) ?></div>
        <div class="bg-slate-50 rounded-lg p-4 mb-6 text-sm text-slate-700 space-y-2">
          <p><strong>หลังบ้าน:</strong> <a class="text-brand underline" href="<?= $loginHref ?>"><?= $loginHref ?></a></p>
          <p><strong>หน้าเว็บ:</strong> <a class="text-brand underline" href="<?= $siteHome ?>"><?= $siteHome ?></a></p>
          <p><strong>บัญชี:</strong> <?= htmlspecialchars($prefill['admin_user']) ?> / (รหัสที่ตั้งไว้)</p>
          <?php if (is_array($seedStats)): ?>
          <p class="text-emerald-700">นำเข้าข้อมูลเริ่มต้นแล้ว: แผน <?= (int) ($seedStats['plans'] ?? 0) ?>, บทความ <?= (int) ($seedStats['blogs'] ?? 0) ?>, โปรโมชัน <?= (int) ($seedStats['promos'] ?? 0) ?></p>
          <?php endif; ?>
        </div>
        <ol class="list-decimal list-inside text-sm text-slate-600 space-y-1 mb-6">
          <li>เข้าสู่ระบบหลังบ้าน</li>
          <li>ตรวจเนื้อหา แล้วกด <strong>เผยแพร่เว็บไซต์</strong></li>
          <li>ลบหรือล็อกไฟล์ install ถ้าต้องการความปลอดภัยเพิ่ม</li>
        </ol>
        <a href="<?= $loginHref ?>" class="admin-btn-primary w-full justify-center py-3 mb-3">ไปหน้าเข้าสู่ระบบ</a>
        <?php if (!is_array($seedStats)): ?>
        <a href="<?= $seedHref ?>" class="admin-btn-outline w-full justify-center py-3">นำเข้าข้อมูลเริ่มต้น</a>
        <?php endif; ?>

      <?php else: ?>
        <?php if ($step === 'error'): ?>
        <div class="admin-alert-error mb-6">
          <p class="font-medium mb-1">ติดตั้งไม่สำเร็จ</p>
          <p class="text-xs break-all"><?= htmlspecialchars($message) ?></p>
        </div>
        <div class="bg-amber-50 border border-amber-200 text-amber-900 rounded-lg p-3 mb-6 text-xs space-y-1">
          <p>บนโฮสติ้งส่วนใหญ่ต้อง <strong>สร้างฐานข้อมูลใน cPanel ก่อน</strong> แล้วใส่ชื่อ/ยูสเซอร์/รหัสที่นี่</p>
          <p>Host มักเป็น <code>localhost</code></p>
        </div>
        <?php endif; ?>

        <?php if ($errors): ?>
        <div class="admin-alert-error mb-6 text-sm">
          <ul class="list-disc list-inside">
            <?php foreach ($errors as $err): ?><li><?= htmlspecialchars($err) ?></li><?php endforeach; ?>
          </ul>
        </div>
        <?php endif; ?>

        <div class="bg-slate-50 rounded-lg p-3 mb-6 text-xs text-slate-600">
          ตรวจพบ path: <code>SITE_URL=<?= htmlspecialchars($siteUrl === '' ? '(root)' : $siteUrl) ?></code>
          · <code>ADMIN_URL=<?= htmlspecialchars($adminUrl) ?></code>
        </div>

        <form method="POST" class="space-y-4">
          <div>
            <label class="admin-label">DB Host</label>
            <input type="text" name="db_host" class="admin-input" value="<?= htmlspecialchars($prefill['db_host']) ?>" required placeholder="localhost">
          </div>
          <div>
            <label class="admin-label">ชื่อฐานข้อมูล (Database name)</label>
            <input type="text" name="db_name" class="admin-input" value="<?= htmlspecialchars($prefill['db_name']) ?>" required placeholder="จาก cPanel → MySQL Databases">
          </div>
          <div>
            <label class="admin-label">DB Username</label>
            <input type="text" name="db_user" class="admin-input" value="<?= htmlspecialchars($prefill['db_user']) ?>" required>
          </div>
          <div>
            <label class="admin-label">DB Password</label>
            <input type="password" name="db_pass" class="admin-input" value="<?= htmlspecialchars($prefill['db_pass']) ?>">
          </div>
          <hr class="border-slate-100">
          <div class="grid sm:grid-cols-2 gap-4">
            <div>
              <label class="admin-label">ชื่อผู้ใช้แอดมิน</label>
              <input type="text" name="admin_user" class="admin-input" value="<?= htmlspecialchars($prefill['admin_user']) ?>" required>
            </div>
            <div>
              <label class="admin-label">รหัสผ่านแอดมิน</label>
              <input type="text" name="admin_pass" class="admin-input" value="<?= htmlspecialchars($prefill['admin_pass']) ?>" required minlength="6">
            </div>
          </div>
          <div>
            <label class="admin-label">ชื่อที่แสดง</label>
            <input type="text" name="admin_name" class="admin-input" value="<?= htmlspecialchars($prefill['admin_name']) ?>">
          </div>
          <label class="flex items-center gap-2 text-sm text-slate-600 cursor-pointer">
            <input type="checkbox" name="run_seed" value="1" <?= $prefill['run_seed'] ? 'checked' : '' ?> class="rounded border-slate-300 text-brand">
            นำเข้าข้อมูลเริ่มต้น (แผน / บทความ / โปรโมชัน) จากไฟล์เว็บทันที
          </label>
          <button type="submit" class="admin-btn-primary w-full justify-center py-3">ติดตั้งฐานข้อมูล</button>
        </form>
      <?php endif; ?>
    </div>
  </div>
</body>
</html>
