<?php
/**
 * Hosting installer — prakandd-thailand.com/admin/install.php
 * Compatible with PHP 7.4+
 */

// Show real error on hosting (remove after install works)
error_reporting(E_ALL);
ini_set('display_errors', '1');
ini_set('display_startup_errors', '1');

$lockFile = __DIR__ . DIRECTORY_SEPARATOR . 'install.lock';
$force = isset($_GET['force']) && $_GET['force'] === '1';

$scriptName = isset($_SERVER['SCRIPT_NAME']) ? str_replace('\\', '/', $_SERVER['SCRIPT_NAME']) : '/admin/install.php';
$adminUrl = rtrim(str_replace('\\', '/', dirname($scriptName)), '/');
if ($adminUrl === '' || $adminUrl === '.') {
    $adminUrl = '/admin';
}
$siteUrl = dirname($adminUrl);
if ($siteUrl === '/' || $siteUrl === '\\' || $siteUrl === '.') {
    $siteUrl = '';
}

$step = 'form';
$message = '';
$errors = array();
$seedStats = null;

$prefill = array(
    'db_host' => 'localhost',
    'db_name' => '',
    'db_user' => '',
    'db_pass' => '',
    'admin_user' => 'admin',
    'admin_pass' => 'admin123',
    'admin_name' => 'Administrator',
    'run_seed' => '1',
);

if (is_file($lockFile) && !$force && (!isset($_SERVER['REQUEST_METHOD']) || $_SERVER['REQUEST_METHOD'] !== 'POST')) {
    $step = 'locked';
}

function install_starts_with($haystack, $needle) {
    return $needle === '' || strpos($haystack, $needle) === 0;
}

function install_contains($haystack, $needle) {
    return $needle === '' || strpos($haystack, $needle) !== false;
}

function install_split_sql($sql) {
    $sql = preg_replace('/^CREATE DATABASE.*?;\s*/im', '', $sql);
    $sql = preg_replace('/^USE\s+.*?;\s*/im', '', $sql);
    $parts = preg_split('/;\s*[\r\n]+/', $sql);
    $out = array();
    if (!is_array($parts)) {
        return $out;
    }
    foreach ($parts as $part) {
        $part = trim($part);
        if ($part === '' || install_starts_with($part, '--')) {
            continue;
        }
        $out[] = $part;
    }
    return $out;
}

function install_write_config(array $data) {
    $export = var_export($data, true);
    // Avoid raw "<?php" in source string (some hosts / scanners break on it)
    $php = '<' . "?php\n/** Auto-generated by install.php */\nreturn " . $export . ";\n";
    $path = __DIR__ . DIRECTORY_SEPARATOR . 'config.local.php';
    if (file_put_contents($path, $php) === false) {
        throw new RuntimeException('เขียนไฟล์ config.local.php ไม่ได้ — ตั้งสิทธิ์เขียนให้โฟลเดอร์ admin/');
    }
}

if (isset($_SERVER['REQUEST_METHOD']) && $_SERVER['REQUEST_METHOD'] === 'POST') {
    $prefill['db_host'] = trim((string) (isset($_POST['db_host']) ? $_POST['db_host'] : 'localhost'));
    $prefill['db_name'] = trim((string) (isset($_POST['db_name']) ? $_POST['db_name'] : ''));
    $prefill['db_user'] = trim((string) (isset($_POST['db_user']) ? $_POST['db_user'] : ''));
    $prefill['db_pass'] = (string) (isset($_POST['db_pass']) ? $_POST['db_pass'] : '');
    $prefill['admin_user'] = trim((string) (isset($_POST['admin_user']) ? $_POST['admin_user'] : 'admin'));
    $prefill['admin_pass'] = (string) (isset($_POST['admin_pass']) ? $_POST['admin_pass'] : '');
    $prefill['admin_name'] = trim((string) (isset($_POST['admin_name']) ? $_POST['admin_name'] : 'Administrator'));
    $prefill['run_seed'] = isset($_POST['run_seed']) ? '1' : '';

    if ($prefill['db_host'] === '') {
        $errors[] = 'กรุณากรอก DB Host';
    }
    if ($prefill['db_name'] === '') {
        $errors[] = 'กรุณากรอกชื่อฐานข้อมูล (จาก cPanel)';
    }
    if ($prefill['db_user'] === '') {
        $errors[] = 'กรุณากรอก DB Username (จาก cPanel — ห้ามใช้ root)';
    }
    if ($prefill['admin_user'] === '') {
        $errors[] = 'กรุณากรอกชื่อผู้ใช้แอดมิน';
    }
    if (strlen($prefill['admin_pass']) < 6) {
        $errors[] = 'รหัสผ่านแอดมินอย่างน้อย 6 ตัวอักษร';
    }

    if (!$errors) {
        try {
            if (!class_exists('PDO')) {
                throw new RuntimeException('โฮสต์ยังไม่เปิด PDO — เปิด PHP extension pdo_mysql ใน Plesk/cPanel');
            }

            $dsnServer = 'mysql:host=' . $prefill['db_host'] . ';charset=utf8mb4';
            $pdo = new PDO($dsnServer, $prefill['db_user'], $prefill['db_pass'], array(
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            ));

            $dbName = $prefill['db_name'];
            $safeDb = str_replace('`', '``', $dbName);
            try {
                $pdo->exec('CREATE DATABASE IF NOT EXISTS `' . $safeDb . '` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');
            } catch (Exception $e) {
                // Shared hosting often forbids CREATE DATABASE
            }

            $pdo->exec('USE `' . $safeDb . '`');

            $sqlFile = __DIR__ . DIRECTORY_SEPARATOR . 'setup.sql';
            if (!is_file($sqlFile)) {
                throw new RuntimeException('ไม่พบไฟล์ setup.sql ในโฟลเดอร์ admin/');
            }
            $sql = file_get_contents($sqlFile);
            foreach (install_split_sql($sql) as $stmt) {
                try {
                    $pdo->exec($stmt);
                } catch (Exception $e) {
                    $msg = $e->getMessage();
                    if (!install_contains($msg, 'already exists') && !install_contains($msg, 'Duplicate')) {
                        throw $e;
                    }
                }
            }

            install_write_config(array(
                'DB_HOST' => $prefill['db_host'],
                'DB_NAME' => $prefill['db_name'],
                'DB_USER' => $prefill['db_user'],
                'DB_PASS' => $prefill['db_pass'],
                'SITE_URL' => $siteUrl,
                'ADMIN_URL' => $adminUrl,
            ));

            $hash = password_hash($prefill['admin_pass'], PASSWORD_DEFAULT);
            $check = $pdo->prepare('SELECT id FROM admin_users WHERE username = ?');
            $check->execute(array($prefill['admin_user']));
            $existing = $check->fetch(PDO::FETCH_ASSOC);
            if ($existing) {
                $upd = $pdo->prepare('UPDATE admin_users SET password_hash = ?, display_name = ? WHERE id = ?');
                $upd->execute(array($hash, $prefill['admin_name'], $existing['id']));
            } else {
                $ins = $pdo->prepare('INSERT INTO admin_users (username, password_hash, display_name) VALUES (?,?,?)');
                $ins->execute(array($prefill['admin_user'], $hash, $prefill['admin_name']));
            }

            $faqCount = (int) $pdo->query('SELECT COUNT(*) FROM faq_items')->fetchColumn();
            if ($faqCount === 0) {
                $pdo->exec("INSERT INTO faq_items (question, answer, sort_order, is_active) VALUES
                    ('ประกันชีวิตคืออะไร และทำไมถึงสำคัญ?', 'ประกันชีวิตเป็นเครื่องมือทางการเงินที่ช่วยคุ้มครองครอบครัวของคุณในกรณีที่เกิดเหตุไม่คาดฝัน เป็นการวางแผนทางการเงินที่สำคัญเพื่อให้คนที่คุณรักมีความมั่นคงในอนาคต', 1, 1),
                    ('ต้องใช้เอกสารอะไรบ้างในการสมัครประกัน?', 'เอกสารที่ต้องใช้ ได้แก่ บัตรประชาชน สำเนาทะเบียนบ้าน และเอกสารทางการแพทย์ (ถ้ามี)', 2, 1),
                    ('สามารถเปลี่ยนแผนประกันได้หรือไม่?', 'สามารถเปลี่ยนแผนประกันได้ตามเงื่อนไขของกรมธรรม์ โดยติดต่อตัวแทนหรือฝ่ายบริการลูกค้า', 3, 1),
                    ('เคลมประกันใช้เวลานานเท่าไหร่?', 'ระยะเวลาในการพิจารณาเคลมโดยทั่วไปใช้เวลา 7-15 วันทำการ', 4, 1),
                    ('มีบริการปรึกษาฟรีหรือไม่?', 'มีบริการปรึกษาฟรีจากทีมผู้เชี่ยวชาญของเรา ติดต่อได้ผ่านแบบฟอร์ม โทรศัพท์ หรือ Line Official', 5, 1),
                    ('สามารถจ่ายเบี้ยประกันรายเดือนได้หรือไม่?', 'สามารถเลือกชำระเบี้ยได้หลายรูปแบบ ทั้งรายเดือน ราย 3 เดือน ราย 6 เดือน หรือรายปี ตามแผนที่คุณสมัคร', 6, 1),
                    ('ประกันคุ้มครองตั้งแต่เมื่อไหร่?', 'ความคุ้มครองเริ่มต้นตามเงื่อนไขในกรมธรรม์ โดยทั่วไปมีผลหลังอนุมัติและชำระเบี้ยงวดแรกเรียบร้อยแล้ว', 7, 1),
                    ('ยกเลิกกรมธรรม์ได้หรือไม่?', 'สามารถยกเลิกกรมธรรม์ได้ตามเงื่อนไขที่ระบุในกรมธรรม์ โดยแนะนำให้ปรึกษาตัวแทนก่อนตัดสินใจ', 8, 1)");
            }

            if ($prefill['run_seed'] === '1') {
                require_once __DIR__ . '/config.php';
                require_once __DIR__ . '/includes/db.php';
                require_once __DIR__ . '/includes/seed-import.php';
                $categories = require __DIR__ . '/seed-categories.php';
                $seedStats = runFullSeedImport($categories);
            }

            $host = isset($_SERVER['HTTP_HOST']) ? $_SERVER['HTTP_HOST'] : 'unknown';
            file_put_contents($lockFile, date('c') . ' installed on ' . $host . "\n");
            $step = 'success';
            $message = 'ติดตั้งเรียบร้อยแล้ว';
        } catch (Exception $e) {
            $step = 'error';
            $message = $e->getMessage();
        }
    } else {
        $step = 'form';
    }
}

$h = function ($s) {
    return htmlspecialchars((string) $s, ENT_QUOTES, 'UTF-8');
};
$loginHref = $h($adminUrl . '/login.php');
$seedHref = $h($adminUrl . '/seed.php');
$siteHome = $h(($siteUrl === '' ? '' : $siteUrl) . '/index.html');
?>
<!DOCTYPE html>
<html lang="th">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ติดตั้งระบบ — Agent Thailand</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <script>tailwind.config={theme:{extend:{colors:{brand:'#150f96'}}}}</script>
  <style>
    body{font-family:system-ui,sans-serif;background:#f1f5f9;margin:0}
    .card{background:#fff;border-radius:16px;padding:2rem;box-shadow:0 10px 30px rgba(15,23,42,.08);max-width:36rem;margin:2rem auto}
    .btn{display:block;width:100%;text-align:center;background:#150f96;color:#fff;border:0;border-radius:10px;padding:.85rem 1rem;font-weight:600;cursor:pointer;text-decoration:none}
    .btn:hover{background:#2a1fbb}
    label{display:block;font-size:.85rem;font-weight:600;color:#334155;margin:0 0 .35rem}
    input[type=text],input[type=password]{width:100%;box-sizing:border-box;border:1px solid #cbd5e1;border-radius:8px;padding:.65rem .75rem;margin-bottom:.9rem}
    .err{background:#fef2f2;border:1px solid #fecaca;color:#991b1b;border-radius:10px;padding:.75rem;margin-bottom:1rem;font-size:.9rem}
    .ok{background:#ecfdf5;border:1px solid #a7f3d0;color:#065f46;border-radius:10px;padding:.75rem;margin-bottom:1rem;font-size:.9rem}
    .hint{background:#f8fafc;border-radius:8px;padding:.75rem;font-size:.8rem;color:#64748b;margin-bottom:1rem}
  </style>
</head>
<body>
  <div class="card">
    <h1 style="text-align:center;margin:0 0 .25rem;font-size:1.5rem;color:#0f172a">ติดตั้งระบบ</h1>
    <p style="text-align:center;margin:0 0 1.5rem;color:#64748b;font-size:.9rem">prakandd-thailand.com</p>

    <?php if ($step === 'locked'): ?>
      <div class="ok">ติดตั้งแล้ว — ระบบพร้อมใช้งาน</div>
      <p style="font-size:.85rem;color:#475569">ถ้าต้องติดตั้งใหม่ ลบไฟล์ <code>admin/install.lock</code> หรือเปิด <code>?force=1</code></p>
      <a class="btn" href="<?php echo $loginHref; ?>">ไปหน้าเข้าสู่ระบบ</a>

    <?php elseif ($step === 'success'): ?>
      <div class="ok"><?php echo $h($message); ?></div>
      <p style="font-size:.9rem"><strong>หลังบ้าน:</strong> <a href="<?php echo $loginHref; ?>"><?php echo $loginHref; ?></a></p>
      <p style="font-size:.9rem"><strong>บัญชี:</strong> <?php echo $h($prefill['admin_user']); ?></p>
      <?php if (is_array($seedStats)): ?>
      <p style="font-size:.85rem;color:#065f46">นำเข้าข้อมูลแล้ว: แผน <?php echo (int) (isset($seedStats['plans']) ? $seedStats['plans'] : 0); ?>, บทความ <?php echo (int) (isset($seedStats['blogs']) ? $seedStats['blogs'] : 0); ?>, โปรโมชัน <?php echo (int) (isset($seedStats['promos']) ? $seedStats['promos'] : 0); ?></p>
      <?php endif; ?>
      <a class="btn" href="<?php echo $loginHref; ?>" style="margin-top:1rem">ไปหน้าเข้าสู่ระบบ</a>

    <?php else: ?>
      <?php if ($step === 'error'): ?>
      <div class="err">
        <strong>ติดตั้งไม่สำเร็จ</strong><br>
        <?php echo $h($message); ?>
      </div>
      <div class="hint">
        บนโฮสติ้งต้องสร้าง Database + User ใน <strong>cPanel / Plesk → MySQL</strong> ก่อน<br>
        ห้ามใช้ <code>root</code> — ใช้ยูสเซอร์ที่สร้างเอง และ Host มักเป็น <code>localhost</code>
      </div>
      <?php endif; ?>

      <?php if ($errors): ?>
      <div class="err"><ul style="margin:0;padding-left:1.2rem"><?php foreach ($errors as $err): ?><li><?php echo $h($err); ?></li><?php endforeach; ?></ul></div>
      <?php endif; ?>

      <div class="hint">
        path ที่ตรวจพบ: SITE_URL=<?php echo $h($siteUrl === '' ? '(root)' : $siteUrl); ?>
        · ADMIN_URL=<?php echo $h($adminUrl); ?>
        · PHP <?php echo $h(PHP_VERSION); ?>
      </div>

      <form method="post" action="">
        <label>DB Host</label>
        <input type="text" name="db_host" value="<?php echo $h($prefill['db_host']); ?>" required placeholder="localhost">

        <label>ชื่อฐานข้อมูล (จาก cPanel)</label>
        <input type="text" name="db_name" value="<?php echo $h($prefill['db_name']); ?>" required placeholder="เช่น prakandd_agent">

        <label>DB Username (ห้ามใช้ root)</label>
        <input type="text" name="db_user" value="<?php echo $h($prefill['db_user']); ?>" required>

        <label>DB Password</label>
        <input type="password" name="db_pass" value="<?php echo $h($prefill['db_pass']); ?>">

        <hr style="border:0;border-top:1px solid #e2e8f0;margin:1rem 0">

        <label>ชื่อผู้ใช้แอดมิน</label>
        <input type="text" name="admin_user" value="<?php echo $h($prefill['admin_user']); ?>" required>

        <label>รหัสผ่านแอดมิน</label>
        <input type="text" name="admin_pass" value="<?php echo $h($prefill['admin_pass']); ?>" required minlength="6">

        <label>ชื่อที่แสดง</label>
        <input type="text" name="admin_name" value="<?php echo $h($prefill['admin_name']); ?>">

        <label style="font-weight:500;margin-bottom:1rem">
          <input type="checkbox" name="run_seed" value="1" <?php echo $prefill['run_seed'] ? 'checked' : ''; ?>>
          นำเข้าข้อมูลเริ่มต้น (แผน / บทความ / โปรโมชัน)
        </label>

        <button type="submit" class="btn">ติดตั้งฐานข้อมูล</button>
      </form>
    <?php endif; ?>
  </div>
</body>
</html>
